name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          submodules: 'recursive'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;26.0.10404224" --channel=1 --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null

      - name: Install Rust Toolchain
        run: rustup update && rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Rename Apks
        run: |
          cp app/build/outputs/apk/release/app-universal-release.apk app/build/outputs/apk/release/EhViewer-universal.apk
          cp app/build/outputs/apk/release/app-arm64-v8a-release.apk app/build/outputs/apk/release/EhViewer-arm64-v8a.apk
          cp app/build/outputs/apk/release/app-x86_64-release.apk app/build/outputs/apk/release/EhViewer-x86_64.apk
          cp app/build/outputs/apk/release/app-x86-release.apk app/build/outputs/apk/release/EhViewer-x86.apk
          cp app/build/outputs/apk/release/app-armeabi-v7a-release.apk app/build/outputs/apk/release/EhViewer-armeabi-v7a.apk

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          discussion_category_name: Announcements
          files: |
            app/build/outputs/apk/release/EhViewer-universal.apk
            app/build/outputs/apk/release/EhViewer-arm64-v8a.apk
            app/build/outputs/apk/release/EhViewer-x86_64.apk
            app/build/outputs/apk/release/EhViewer-x86.apk
            app/build/outputs/apk/release/EhViewer-armeabi-v7a.apk
            app/build/outputs/mapping/release/mapping.txt

      - name: Collect Apks
        run: |
          mkdir app/build/outputs/apk/release/fdroid
          cp app/build/outputs/apk/release/app-arm64-v8a-release.apk app/build/outputs/apk/release/fdroid/EhViewer-v$GITHUB_REF_NAME.apk
          cp app/build/outputs/apk/release/app-armeabi-v7a-release.apk app/build/outputs/apk/release/fdroid/EhViewer-v$GITHUB_REF_NAME-armv7.apk

      - name: Push Apks
        uses: Ehviewer-Overhauled/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: app/build/outputs/apk/release/fdroid
          destination-github-username: Ehviewer-Overhauled
          destination-repository-name: fdroid-repo
          user-name: 'github-actions[bot]'
          user-email: 'github-actions[bot]@users.noreply.github.com'
          target-branch: deploy
          create-target-branch: true
          commit-message: Add apks from $GITHUB_REF
          target-directory: fdroid/tmp-apks