name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;24.0.8215888" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: |
          git submodule update --init --recursive
          gradle assembleRelease

      - name: Releases
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: Bump Version
          files: |
            app/build/outputs/apk/release/app-arm64-v8a-release.apk
            app/build/outputs/apk/release/app-x86_64-release.apk
            app/build/outputs/apk/release/app-x86-release.apk
            app/build/outputs/apk/release/app-armeabi-v7a-release.apk
